### PR TITLE
Without Bukkit build

### PR DESCRIPTION
**Pull request by portlek**

### CODE REVIEW

**Comment by dumptruckman** [comment]
Why would I accept this? You appear to have changed it into something for an entirely different purpose.

**Comment by portlek** [comment]
It's working without the Bukkit now so we can use it everywhere such as Java programs, games, discord bots. I just remove the hard dependencies called Bukkit.

**Comment by portlek** [comment]
Or you can create a branch that will have `withoutbukkit` p.r.'s

**Comment by dumptruckman** [comment]
Sorry, I easily miss github notifications in my email. You could simply use json-smart on it's own or even Jackson if you're just interested in storing your stuff in json. The whole point of this library is to implement Bukkit Configuration in json.

**Pull request closed without merging**
